# Generated by Django 3.2.5 on 2021-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dogs_owned',
        ),
        migrations.AddField(
            model_name='client',
            name='dogs_owned',
            field=models.ManyToManyField(blank=True, to='dogs.Dog'),
        ),
    ]
