# Generated by Django 3.2.5 on 2021-07-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_owner'),
        ('users', '0002_auto_20210714_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dogs_owned',
        ),
        migrations.AddField(
            model_name='client',
            name='dogs_owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
        ),
    ]
