# Generated by Django 3.2.5 on 2021-07-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_owner'),
        ('users', '0003_auto_20210714_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dogs_owned',
        ),
        migrations.AddField(
            model_name='client',
            name='dogs_owned',
            field=models.ManyToManyField(blank=True, to='dogs.Dog'),
        ),
    ]
