# Generated by Django 3.2.5 on 2021-07-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210714_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='full_name',
        ),
    ]
