# Generated by Django 3.2.5 on 2021-07-07 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sessions',
            field=models.ManyToManyField(to='training_sessions.Session'),
        ),
        migrations.AddField(
            model_name='session',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time_ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
