# Generated by Django 3.2.5 on 2021-09-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='slot_price',
        ),
    ]
