# Generated by Django 3.2.5 on 2021-07-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='time_created',
        ),
    ]
