# Generated by Django 3.2.5 on 2021-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slot_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
