# Generated by Django 3.2.5 on 2021-07-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0002_session_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_slots',
            field=models.IntegerField(default=0),
        ),
    ]
