# Generated by Django 3.2.5 on 2021-07-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0002_session_slot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='adjusted_slot_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
