# Generated by Django 3.2.5 on 2021-07-13 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0002_auto_20210713_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
