# Generated by Django 3.2.5 on 2021-07-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0003_auto_20210713_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
    ]
