# Generated by Django 3.2.5 on 2021-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0004_remove_report_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='time_ended',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='time_started',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
