# Generated by Django 3.2.5 on 2021-07-15 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0005_session_slots_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='started',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
