# Generated by Django 3.2.5 on 2021-07-19 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('all_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
