# Generated by Django 3.2.5 on 2021-07-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age_months',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_years',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='dog',
            name='vet_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='vet_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
