# Generated by Django 3.2.5 on 2021-07-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='img_media/profiles/'),
        ),
    ]
