# Generated by Django 3.2.5 on 2021-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='extra_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='no_match_dogs',
            field=models.ManyToManyField(blank=True, default=None, related_name='_dogs_dog_no_match_dogs_+', to='dogs.Dog'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
    ]
