# Generated by Django 3.2.5 on 2021-07-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dog_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='img_media',
            field=models.FileField(blank=True, null=True, upload_to='img_media/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='img_media/profiles/'),
        ),
    ]
