# Generated by Django 3.2.5 on 2021-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
        ('dogs', '0003_auto_20210707_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='booked_sessions',
            field=models.ManyToManyField(blank=True, default=None, to='training_sessions.Session'),
        ),
    ]
