# Generated by Django 3.2.5 on 2021-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20210708_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='img_media',
            field=models.FileField(blank=True, null=True, upload_to='static/img_media/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='static/img_media/profiles/'),
        ),
    ]
