# Generated by Django 3.2.5 on 2021-07-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageFiles',
            new_name='MediaFile',
        ),
        migrations.RemoveField(
            model_name='videofiles',
            name='dog',
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
        migrations.DeleteModel(
            name='VideoFiles',
        ),
    ]
