# Generated by Django 3.2.5 on 2021-07-19 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0002_alter_userprofilepic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogmediafile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/image_media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='dogprofilepic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/profile_pics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='usermediafile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/image_media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='userprofilepic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/profile_pics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
