# Generated by Django 3.2.5 on 2021-07-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='name',
            new_name='full_name',
        ),
    ]
