# Generated by Django 3.2.5 on 2021-07-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_files', '0001_initial'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_files.userprofilepic'),
        ),
    ]
