# Generated by Django 3.2.5 on 2021-07-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='field_of_expertise',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('Walker', 'Walker'), ('Hiker', 'Hiker'), ('Runner', 'Runner'), ('Behaviorist', 'Behaviorist')], max_length=11),
        ),
    ]
