# Generated by Django 3.2.5 on 2021-07-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
