# Generated by Django 3.2.5 on 2021-07-07 16:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_alter_trainer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
