# Generated by Django 3.2.5 on 2021-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_alter_trainer_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='field_of_expertise',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('Walker', 'Walker'), ('Hiker', 'Hiker'), ('Runner', 'Runner'), ('Behavioral', 'Behavioral')], max_length=10),
        ),
    ]
