# Generated by Django 3.2.5 on 2021-07-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0003_alter_trainer_field_of_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='field_of_expertise',
            field=models.CharField(choices=[('T', 'Trainer'), ('W', 'Walker'), ('H', 'Hiker'), ('R', 'Runner'), ('B', 'Behavioral')], max_length=1),
        ),
    ]
