# Generated by Django 3.2.5 on 2021-07-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='all_messages.message')),
                ('seen_by_user', models.BooleanField(default=False)),
            ],
            bases=('all_messages.message',),
        ),
    ]
